function run_plot_tau_e_sensitivity()
addpath(genpath('../matlab_functions/'));
% Plot the tau_e sensitivity analysis for the PDG model (flat bounds).
%
% Loads pre-computed statistics from tau_e_sensitivity_stats.mat
% (generated by run_make_sim_tau_e.m) and produces a 3-panel figure
% showing how the three gaze signatures vary with tau_e:
%
%   Panel A – RT-aligned gaze cascade
%   Panel B – Influence of last fixation on choice (log-odds vs sum value)
%   Panel C – Delta-Dwell vs RT (consistent & inconsistent choices)
%
% Each tau_e value is shown in a different color, ranging from blue
% (100 ms) to red (400 ms).
%
% Output: fig_tau_e_sensitivity.pdf
%
% USAGE
%   cd code_n_data_for_sharing/sensitivity_tau_e
%   run_plot_tau_e_sensitivity()

%% ---- Load results ---------------------------------------------------
fprintf('Loading tau_e_sensitivity_stats.mat ...\n');
R = load('tau_e_sensitivity_stats.mat');

tau_e_vals = R.tau_e_vals;
nTau       = numel(tau_e_vals);

%% ---- Color scheme ---------------------------------------------------
% Gradient from blue (small tau_e) to red (large tau_e)
colors = [
    0.18,  0.40,  0.82;   % tau_e = 100 ms  (blue)
    0.10,  0.68,  0.50;   % tau_e = 200 ms  (teal)
    0.92,  0.55,  0.08;   % tau_e = 300 ms  (orange)
    0.82,  0.08,  0.14;   % tau_e = 400 ms  (red)
];

% Build legend labels
leg_labels = arrayfun(@(x) sprintf('\\mu_e = %d ms', round(x * 1000)), ...
                      tau_e_vals, 'UniformOutput', false);

%% ---- Helper: mean ± SEM across subjects for a given matrix ----------
%  X is (n_subj × n_bins); returns row vectors mean, sem.
mean_sem = @(X) deal(nanmean(X, 1), ...
                     nanstd(X, 0, 1) ./ sqrt(max(sum(~isnan(X), 1), 1)));

%% ---- Create figure --------------------------------------------------
fh = figure('Color', 'w', ...
            'Units', 'centimeters', ...
            'Position', [2, 2, 22, 7]);

set(gcf,'Position',[4.18042      9.73667      23.0717      6.56167]);

lw_data  = 1.8;    % line width for data curves
lw_shade = 0.6;    % line width for SEM shading
fs_ax    = 9;      % font size for axes
ms       = 5;      % marker size

% ======================================================================
%% Panel A – RT-aligned gaze cascade
%   R.gaze_rt_subj is (nTau × n_subj × n_t_rt)
%   R.gaze_rt_t    is the time vector (1 × n_t_rt), range ~ [-1, 0] s
% ======================================================================
ax1 = subplot(1, 3, 1);
hold on;

T_RT = R.gaze_rt_t(:)';   % ensure row vector

hl = gobjects(nTau, 1);
for itau = 1:nTau
    X = squeeze(R.gaze_rt_subj(itau, :, :));   % n_subj × n_t_rt
    [mu, se] = mean_sem(X);

    % Shaded SEM region
    fill_x = [T_RT, fliplr(T_RT)];
    fill_y = [mu + se, fliplr(mu - se)];
    fill(fill_x, fill_y, colors(itau,:), ...
         'FaceAlpha', 0.18, 'EdgeColor', 'none');

    % Mean line
    hl(itau) = plot(T_RT, mu, '-', ...
                    'Color', colors(itau,:), 'LineWidth', lw_data);
end

% Reference line at 0.5 (chance)
plot([-1.25, 0.05], [0.5, 0.5], 'k:', 'LineWidth', 0.8);

xlabel('Time from RT [s]',         'FontSize', fs_ax);
ylabel('P(look at chosen item)',   'FontSize', fs_ax);
title('Gaze cascade (RT-aligned)', 'FontSize', fs_ax, 'FontWeight', 'normal');
xlim([-1.0, 0.05]);
ylim([0.38, 1.02]);


% set(ax1, 'FontSize', fs_ax, 'Box', 'off', 'TickDir', 'out');

% Legend (only in panel A to save space)
% legend(hl, leg_labels, 'Location', 'northwest', ...
%        'Box', 'off', 'FontSize', fs_ax - 1);

legend_color(leg_labels, hl);


% ======================================================================
%% Panel B – Influence of last fixation (log-odds vs sum value)
%   R.lf_x, R.lf_y, R.lf_s are (nTau × n_bins)
%   These are extracted directly from calc_and_plot_split_sum_value
%   (same scale as fn_run_plot_best.m panel 7)
% ======================================================================
ax2 = subplot(1, 3, 2);
hold on;

for itau = 1:nTau
    x_vals = R.lf_x(itau, :);
    y_vals = R.lf_y(itau, :);
    s_vals = R.lf_s(itau, :);

    % Remove any NaN padding
    ok = ~isnan(x_vals);
    x_vals = x_vals(ok);
    y_vals = y_vals(ok);
    s_vals = s_vals(ok);

    fill_x = [x_vals, fliplr(x_vals)];
    fill_y = [y_vals + s_vals, fliplr(y_vals - s_vals)];
    fill(fill_x, fill_y, colors(itau,:), ...
         'FaceAlpha', 0.18, 'EdgeColor', 'none');
    hold all
    plot(x_vals, y_vals, '-o', ...
         'Color', colors(itau,:), 'LineWidth', lw_data, ...
         'MarkerSize', ms, 'MarkerFaceColor', colors(itau,:), ...
         'MarkerEdgeColor', 'none');
end

% Reference line at 0 (no last-fix bias)
xL = xlim;
plot(xL, [0, 0], 'k:', 'LineWidth', 0.8);

xlabel('Overall value (left + right)', 'FontSize', fs_ax);
% ylabel({'Influence of last-fixation on choice (\beta)'}, 'FontSize', fs_ax);
ylabel({'Association between last dwell','and choice (\beta)'}, 'FontSize', fs_ax);
% title('Last-fixation influence',   'FontSize', fs_ax, 'FontWeight', 'normal');
set(ax2, 'FontSize', fs_ax, 'Box', 'off', 'TickDir', 'out');

% ======================================================================
%% Panel C – Delta-Dwell vs RT (consistent / inconsistent)
%   R.dd_con_t, R.dd_con_y, R.dd_con_s  (nTau × n_rt_bins)
%   R.dd_inc_y, R.dd_inc_s              (nTau × n_rt_bins)
%   RT bin centers are per-tau_e (from index_prctile_by_group);
%   use the mean of the first tau_e's centers as the x-axis (they are
%   nearly identical across tau_e because they depend only on RT/group).
% ======================================================================
ax3 = subplot(1, 3, 3);
hold on;

for itau = 1:nTau
    rt_ctrs = R.dd_con_t(itau, :);   % 1 × n_rt_bins

    % Consistent choices
    muc = R.dd_con_y(itau, :);
    sec = R.dd_con_s(itau, :);

    % Inconsistent choices
    mui = R.dd_inc_y(itau, :);
    sei = R.dd_inc_s(itau, :);

    fill_x = [rt_ctrs, fliplr(rt_ctrs)];

    fill(fill_x, [muc + sec, fliplr(muc - sec)], colors(itau,:), ...
         'FaceAlpha', 0.18, 'EdgeColor', 'none');
    plot(rt_ctrs, muc, '-', ...
         'Color', colors(itau,:), 'LineWidth', lw_data);

    fill(fill_x, [mui + sei, fliplr(mui - sei)], colors(itau,:), ...
         'FaceAlpha', 0.10, 'EdgeColor', 'none');
    plot(rt_ctrs, mui, '--', ...
         'Color', colors(itau,:), 'LineWidth', lw_data * 0.8);
end

% Reference line at 0
xL = xlim;
plot(xL, [0, 0], 'k:', 'LineWidth', 0.8);

% Small legend for line style
lh_con = plot(nan, nan, 'k-',  'LineWidth', lw_data,       'DisplayName', 'Consistent');
lh_inc = plot(nan, nan, 'k--', 'LineWidth', lw_data * 0.8, 'DisplayName', 'Inconsistent');
hl = legend([lh_con, lh_inc], 'Location', 'southwest', 'Box', 'off', 'FontSize', fs_ax - 1);
% set(hl,[0.6916    0.1399    0.2134    0.7851]);

xlabel('Response time [s]',  'FontSize', fs_ax);
ylabel('\DeltaDwell [s]',    'FontSize', fs_ax);
% title('\DeltaDwell vs RT',  'FontSize', fs_ax, 'FontWeight', 'normal');
set(ax3, 'FontSize', fs_ax, 'Box', 'off', 'TickDir', 'out');

set(ax3,'xlim',[0.9,4.8]);
set(ax2,'xlim',[1.2,15])

displace_ax(ax1,-0.03,1);
displace_ax(ax3,0.03,1);

%% ---- Panel labels (A, B, C) -----------------------------------------
annotation('textbox', [ax1.Position(1) - 0.03, ax1.Position(2) + ax1.Position(4) + 0.04, 0.02, 0.05], ...
           'String', 'A', 'FontSize', 11, 'FontWeight', 'bold', ...
           'EdgeColor', 'none', 'FitBoxToText', 'on');
annotation('textbox', [ax2.Position(1) + 0, ax2.Position(2) + ax2.Position(4) + 0.04, 0.02, 0.05], ...
           'String', 'B', 'FontSize', 11, 'FontWeight', 'bold', ...
           'EdgeColor', 'none', 'FitBoxToText', 'on');
annotation('textbox', [ax3.Position(1) + 0, ax3.Position(2) + ax3.Position(4) + 0.04, 0.02, 0.05], ...
           'String', 'C', 'FontSize', 11, 'FontWeight', 'bold', ...
           'EdgeColor', 'none', 'FitBoxToText', 'on');

%% ---- Export to PDF --------------------------------------------------
figname = 'fig_tau_e_sensitivity';
fprintf('Saving %s.pdf ...\n', figname);
set(fh, 'PaperUnits', 'centimeters', 'PaperSize', [22, 7], ...
        'PaperPosition', [0, 0, 22, 7]);
print(fh, figname, '-dpdf', '-painters', '-r300');

% save also to the figures folder
figname = '../../figures/fig_tau_e_sensitivity';
print(fh, figname, '-dpdf', '-painters', '-r300');
fprintf('Done.\n');

end
